title: [Juan Pablo Cortes]
logo: /assets/img/logo.jpg
description: [Estudiante de ingeniería de sistemas | Programador ReactJs]

minima: 

  social_links:
     linkedin: hola

theme: jekyll-theme-minimal