title: [Juan Pablo Cortes]
logo: /assets/img/logo.jpg
description: [Estudiante de ingeniería de sistemas | Programador ReactJs]
linkedin: https://www.linkedin.com/in/juan-pablo-cortes-gonzalez-b5ab591b8/
imglink: /assets/img/Logo-Linkedin.png
theme: jekyll-theme-minimal